name: python

volumes:
  root:

services:
  python:
    hostname: python
    build:
      context: .
      args:
        UBUNTU_MIRROR: ${UBUNTU_MIRROR:-http://mirror.xtom.com.hk/ubuntu/}
    volumes:
      - root:/root
